### ISSUE TITLE
UIOU

### ISSUE THREAD

**Issue by zhu2014yi** [yiakwy/yiakwy.github.io#3]
请问你的uiou loss是怎么计算呢

**Comment by yiakwy** [comment]
First compute iou, perhaps you have already know about it either using pure numpy or Tensor with broadcasting:

```
h = max(0, y2 - y1)
w = max(0, x2 - x1)
where x1, y1 topLeft point of "intersected areas"
           x2, y2 bottomRight point of "intersected areas" using tensor max and min to compute them
overlap = float(w * h)
iou = overloap / (union + 1e-6)
```

Second, you need to define negative punishment if they share 0 overlap:

1. after you got iou, compute new x1, y1, x2, y2 for chul_area:
```
h = max(0, y2 - y1)
w = max(0, x2 - x1)
where x1, y1 topLeft point of "aabb of two boxes"
           x2, y2 bottomRight point of "aabb fo two boxes" using tensor max and min to compute them
chul_area = float(w*h) #! they are different from the above, please draw a picture to see it
```

2. compute negative punishment:

```
union = left_area + right_area - overlap
y0 = (chul_area - union) / chul_area

# normalize it to (-1, 0)
y = (y0 - ymin) / (ymax - ymin)

where ymax = 1.0 (actually y -> 1.0 when the distance between two boxes is infinite)
ymin = (fixed_chul - (left_area + right_area)) / float(fixed_chul)

fixed_chul is computed when overlap is exactly 0, by using (w1 + w2) *  (h1 + h2)
```

3. Finally combine them together

```
uiou = (1-x)*iou - x *(y0 - ymin) / (ymax - ymin)
```

4. [Optionally] you since uiou samples from (-1, 1), you can transform them to (0, 1) in some tasks such as KM algorithm linear assignment:

```
distance = (1 + uiou ) / 2.
``` 

As you can see from numeric simulation, this can achieve much better numeric peformances and representation than IoU, GIoU, and latest variations of IoU ...
